/*======================================================================
  Layer  : BL_DM
  Object : DIM_CUSTOMERS_SCD
  Type   : DDL + DML
  SCD    : Type 2
  DB     : PostgreSQL
  Notes  :
    - Rerunnable / reusable (IF NOT EXISTS, NOT EXISTS)
    - Default row included
    - NULL handling via COALESCE
    - DATE fields only
    - Change detection uses IS DISTINCT FROM (NULL-safe)
    - PK generated by SEQUENCE via DEFAULT (no nextval in INSERT)
    - LEFT JOIN approach for compare
    - COMMIT after DML blocks (BEGIN/COMMIT to avoid "no transaction" warning)
  Sources:
    - sa_b2c.ext_b2c columns used: customer_id, customer_name, customer_email, device_type, payment_method, source_system
    - sa_b2b.ext_b2b columns used: customer_id, company_name, company_industry, tax_id, source_system
======================================================================*/

--======================================================================
-- 0. SCHEMA
--======================================================================
CREATE SCHEMA IF NOT EXISTS bl_dm;

--======================================================================
-- 1. SEQUENCE (surrogate PK)
--======================================================================
CREATE SEQUENCE IF NOT EXISTS bl_dm.seq_dim_customers_scd
    START WITH 1
    INCREMENT BY 1;

--======================================================================
-- 2. TABLE (NO DEFAULTS)
--======================================================================
CREATE TABLE IF NOT EXISTS bl_dm.dim_customers_scd (
    customer_surr_id   BIGINT PRIMARY KEY,              
    customer_src_id    VARCHAR(100) NOT NULL,
    customer_source    VARCHAR(100) NOT NULL,           -- 'B2C' / 'B2B'

    customer_name      VARCHAR(255) NOT NULL,
    customer_email     VARCHAR(255) NOT NULL,
    device_type        VARCHAR(50)  NOT NULL,
    payment_method     VARCHAR(50)  NOT NULL,
    company_name       VARCHAR(255) NOT NULL,
    company_industry   VARCHAR(100) NOT NULL,
    tax_id             VARCHAR(50)  NOT NULL,

    start_dt           DATE NOT NULL,
    end_dt             DATE NOT NULL,
    is_active          VARCHAR(1)   NOT NULL,

    insert_dt          DATE NOT NULL,
    source_system      VARCHAR(50)  NOT NULL,
    source_entity      VARCHAR(50)  NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_customers_scd_active
ON bl_dm.dim_customers_scd (customer_src_id, customer_source)
WHERE is_active = 'Y';


--======================================================================
-- 3. DEFAULT ROW
--======================================================================
BEGIN;

INSERT INTO bl_dm.dim_customers_scd (
    customer_surr_id,
    customer_src_id,
    customer_source,
    customer_name,
    customer_email,
    device_type,
    payment_method,
    company_name,
    company_industry,
    tax_id,
    start_dt,
    end_dt,
    is_active,
    insert_dt,
    source_system,
    source_entity
)
SELECT
    -1,
    'n.a.',
    'MANUAL',
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    DATE '1990-01-01',
    DATE '9999-12-31',
    'Y',
    CURRENT_DATE,
    'MANUAL',
    'MANUAL'
WHERE NOT EXISTS (
    SELECT 1
    FROM bl_dm.dim_customers_scd
    WHERE customer_surr_id = -1
);

COMMIT;

--======================================================================
-- 4. SCD2 LOAD
--======================================================================

--======================================================================
-- 4.1 CLOSE OLD VERSION (changed active rows)
--======================================================================
BEGIN;

WITH src AS (
    /* -------- B2C customers -------- */
    SELECT
        CAST(c.customer_id AS VARCHAR(100))             AS customer_src_id,
        'B2C'                                           AS customer_source,

        MAX(COALESCE(c.customer_name,  'n.a.'))         AS customer_name,
        MAX(COALESCE(c.customer_email, 'n.a.'))         AS customer_email,
        MAX(COALESCE(c.device_type,    'n.a.'))         AS device_type,
        MAX(COALESCE(c.payment_method, 'n.a.'))         AS payment_method,

        'n.a.'                                          AS company_name,
        'n.a.'                                          AS company_industry,
        'n.a.'                                          AS tax_id,

        MAX(COALESCE(c.source_system, 'n.a.'))          AS source_system,
        'ext_b2c'                                       AS source_entity
    FROM sa_b2c.ext_b2c c
    WHERE c.customer_id IS NOT NULL
    GROUP BY c.customer_id

    UNION ALL

    /* -------- B2B customers -------- */
    SELECT
        CAST(b.customer_id AS VARCHAR(100))             AS customer_src_id,
        'B2B'                                           AS customer_source,

        'n.a.'                                          AS customer_name,
        'n.a.'                                          AS customer_email,
        'n.a.'                                          AS device_type,
        'n.a.'                                          AS payment_method,

        MAX(COALESCE(b.company_name,     'n.a.'))       AS company_name,
        MAX(COALESCE(b.company_industry, 'n.a.'))       AS company_industry,
        MAX(COALESCE(b.tax_id,           'n.a.'))       AS tax_id,

        MAX(COALESCE(b.source_system, 'n.a.'))          AS source_system,
        'ext_b2b'                                       AS source_entity
    FROM sa_b2b.ext_b2b b
    WHERE b.customer_id IS NOT NULL
    GROUP BY b.customer_id
),
cmp AS (
    /* Compare incoming source with current active version in DIM */
    SELECT
        s.*,
        d.customer_surr_id                               AS active_customer_surr_id,

        d.customer_name                                  AS d_customer_name,
        d.customer_email                                 AS d_customer_email,
        d.device_type                                    AS d_device_type,
        d.payment_method                                 AS d_payment_method,
        d.company_name                                   AS d_company_name,
        d.company_industry                               AS d_company_industry,
        d.tax_id                                         AS d_tax_id
    FROM src s
    LEFT JOIN bl_dm.dim_customers_scd d
      ON d.customer_src_id = s.customer_src_id
     AND d.customer_source = s.customer_source
     AND d.is_active = 'Y'
),
chg AS (
    /* Identify only changed records among active ones */
    SELECT c.active_customer_surr_id AS customer_surr_id
    FROM cmp c
    WHERE c.active_customer_surr_id IS NOT NULL
      AND (
           c.customer_name     IS DISTINCT FROM c.d_customer_name
        OR c.customer_email    IS DISTINCT FROM c.d_customer_email
        OR c.device_type       IS DISTINCT FROM c.d_device_type
        OR c.payment_method    IS DISTINCT FROM c.d_payment_method
        OR c.company_name      IS DISTINCT FROM c.d_company_name
        OR c.company_industry  IS DISTINCT FROM c.d_company_industry
        OR c.tax_id            IS DISTINCT FROM c.d_tax_id
      )
)
UPDATE bl_dm.dim_customers_scd d
SET
    end_dt    = CURRENT_DATE - 1,
    is_active = 'N'
WHERE d.customer_surr_id IN (SELECT customer_surr_id FROM chg)
  AND d.is_active = 'Y'
  AND d.end_dt = DATE '9999-12-31';

COMMIT;

--======================================================================
-- 4.2 INSERT NEW VERSION (new keys + changed keys)
--      PK generated in DML via nextval(...)
--======================================================================
BEGIN;

WITH src AS (
    /* -------- B2C customers -------- */
    SELECT
        CAST(c.customer_id AS VARCHAR(100))             AS customer_src_id,
        'B2C'                                           AS customer_source,

        MAX(COALESCE(c.customer_name,  'n.a.'))         AS customer_name,
        MAX(COALESCE(c.customer_email, 'n.a.'))         AS customer_email,
        MAX(COALESCE(c.device_type,    'n.a.'))         AS device_type,
        MAX(COALESCE(c.payment_method, 'n.a.'))         AS payment_method,

        'n.a.'                                          AS company_name,
        'n.a.'                                          AS company_industry,
        'n.a.'                                          AS tax_id,

        MAX(COALESCE(c.source_system, 'n.a.'))          AS source_system,
        'ext_b2c'                                       AS source_entity
    FROM sa_b2c.ext_b2c c
    WHERE c.customer_id IS NOT NULL
    GROUP BY c.customer_id

    UNION ALL

    /* -------- B2B customers -------- */
    SELECT
        CAST(b.customer_id AS VARCHAR(100))             AS customer_src_id,
        'B2B'                                           AS customer_source,

        'n.a.'                                          AS customer_name,
        'n.a.'                                          AS customer_email,
        'n.a.'                                          AS device_type,
        'n.a.'                                          AS payment_method,

        MAX(COALESCE(b.company_name,     'n.a.'))       AS company_name,
        MAX(COALESCE(b.company_industry, 'n.a.'))       AS company_industry,
        MAX(COALESCE(b.tax_id,           'n.a.'))       AS tax_id,

        MAX(COALESCE(b.source_system, 'n.a.'))          AS source_system,
        'ext_b2b'                                       AS source_entity
    FROM sa_b2b.ext_b2b b
    WHERE b.customer_id IS NOT NULL
    GROUP BY b.customer_id
),
cmp AS (
    SELECT
        s.*,
        d.customer_surr_id                               AS active_customer_surr_id,

        d.customer_name                                  AS d_customer_name,
        d.customer_email                                 AS d_customer_email,
        d.device_type                                    AS d_device_type,
        d.payment_method                                 AS d_payment_method,
        d.company_name                                   AS d_company_name,
        d.company_industry                               AS d_company_industry,
        d.tax_id                                         AS d_tax_id
    FROM src s
    LEFT JOIN bl_dm.dim_customers_scd d
      ON d.customer_src_id = s.customer_src_id
     AND d.customer_source = s.customer_source
     AND d.is_active = 'Y'
)
INSERT INTO bl_dm.dim_customers_scd (
    customer_surr_id,        
    customer_src_id,
    customer_source,
    customer_name,
    customer_email,
    device_type,
    payment_method,
    company_name,
    company_industry,
    tax_id,
    start_dt,
    end_dt,
    is_active,
    insert_dt,
    source_system,
    source_entity
)
SELECT
    nextval('bl_dm.seq_dim_customers_scd') AS customer_surr_id,   
    COALESCE(c.customer_src_id, 'n.a.')    AS customer_src_id,
    COALESCE(c.customer_source, 'n.a.')    AS customer_source,
    COALESCE(c.customer_name, 'n.a.')      AS customer_name,
    COALESCE(c.customer_email, 'n.a.')     AS customer_email,
    COALESCE(c.device_type, 'n.a.')        AS device_type,
    COALESCE(c.payment_method, 'n.a.')     AS payment_method,
    COALESCE(c.company_name, 'n.a.')       AS company_name,
    COALESCE(c.company_industry, 'n.a.')   AS company_industry,
    COALESCE(c.tax_id, 'n.a.')             AS tax_id,
    CURRENT_DATE                            AS start_dt,          
    DATE '9999-12-31'                       AS end_dt,           
    'Y'                                     AS is_active,         
    CURRENT_DATE                            AS insert_dt,
    COALESCE(c.source_system, 'n.a.')       AS source_system,
    COALESCE(c.source_entity, 'n.a.')       AS source_entity
FROM cmp c
WHERE
    c.active_customer_surr_id IS NULL
    OR (
           c.customer_name     IS DISTINCT FROM c.d_customer_name
        OR c.customer_email    IS DISTINCT FROM c.d_customer_email
        OR c.device_type       IS DISTINCT FROM c.d_device_type
        OR c.payment_method    IS DISTINCT FROM c.d_payment_method
        OR c.company_name      IS DISTINCT FROM c.d_company_name
        OR c.company_industry  IS DISTINCT FROM c.d_company_industry
        OR c.tax_id            IS DISTINCT FROM c.d_tax_id
    );

COMMIT;



--======================================================================
-- 1. DEFAULT ROW CHECK (-1)
--======================================================================
/* Expected: cnt = 1 */
SELECT
    'CHK_01_DEFAULT_ROW' AS check_name,
    COUNT(*)             AS cnt
FROM bl_dm.dim_customers_scd
WHERE customer_surr_id = -1;

--======================================================================
-- 2. NO DUPLICATE ACTIVE ROWS PER BUSINESS KEY
--======================================================================
/* Expected: problem_rows = 0 */
SELECT
    'CHK_02_DUPLICATE_ACTIVE' AS check_name,
    COUNT(*)                  AS problem_rows
FROM (
    SELECT customer_src_id, customer_source
    FROM bl_dm.dim_customers_scd
    WHERE is_active = 'Y'
    GROUP BY customer_src_id, customer_source
    HAVING COUNT(*) > 1
) t;

--======================================================================
-- 3. ACTIVE FLAG CONSISTENCY WITH END_DT
--======================================================================
/* Expected: problem_rows = 0
   Rule:
     - Active row must have end_dt = 9999-12-31
     - Inactive row must have end_dt <> 9999-12-31
*/
SELECT
    'CHK_03_ACTIVE_ENDDT_CONSISTENCY' AS check_name,
    COUNT(*)                          AS problem_rows
FROM bl_dm.dim_customers_scd
WHERE (is_active = 'Y' AND end_dt <> DATE '9999-12-31')
   OR (is_active = 'N' AND end_dt =  DATE '9999-12-31');

--======================================================================
-- 4. DATE RANGE VALIDITY
--======================================================================
/* Expected: problem_rows = 0
   Rule: start_dt must be <= end_dt
*/
SELECT
    'CHK_04_DATE_RANGE_VALID' AS check_name,
    COUNT(*)                  AS problem_rows
FROM bl_dm.dim_customers_scd
WHERE start_dt > end_dt;

--======================================================================
-- 5. NO OVERLAPPING PERIODS PER BUSINESS KEY
--======================================================================
/* Expected: problem_rows = 0
   Rule: for the same business key, validity periods must not overlap
*/
SELECT
    'CHK_05_NO_OVERLAPS' AS check_name,
    COUNT(*)             AS problem_rows
FROM (
    SELECT 1
    FROM bl_dm.dim_customers_scd a
    JOIN bl_dm.dim_customers_scd b
      ON a.customer_src_id = b.customer_src_id
     AND a.customer_source = b.customer_source
     AND a.customer_surr_id < b.customer_surr_id
    WHERE a.start_dt <= b.end_dt
      AND b.start_dt <= a.end_dt
) t;

/*======================================================================
  Layer  : BL_DM
  Object : DIM_IDEAS
  Type   : DDL + DML (SCD1)
  Sources:
    - sa_b2c.ext_b2c
    - sa_b2b.ext_b2b
======================================================================*/

--======================================================================
-- 1. SEQUENCE
--======================================================================
CREATE SEQUENCE IF NOT EXISTS bl_dm.seq_dim_ideas
    START WITH 1
    INCREMENT BY 1;

--======================================================================
-- 2. TABLE (NO DEFAULTS)
--======================================================================
CREATE TABLE IF NOT EXISTS bl_dm.dim_ideas (
    idea_surr_id           BIGINT PRIMARY KEY,      
    idea_src_id            VARCHAR(100) NOT NULL,

    idea_title             VARCHAR(500) NOT NULL,
    idea_version           VARCHAR(50)  NOT NULL,    

    idea_category_id       VARCHAR(100) NOT NULL,
    idea_category_name     VARCHAR(255) NOT NULL,

    idea_subcategory_id    VARCHAR(100) NOT NULL,
    idea_subcategory_name  VARCHAR(255) NOT NULL,

    industry_domain_src_id VARCHAR(100) NOT NULL,
    industry_domain_name   VARCHAR(255) NOT NULL,

    author_src_id          VARCHAR(100) NOT NULL,
    author_name            VARCHAR(255) NOT NULL,

    insert_dt              DATE NOT NULL,
    update_dt              DATE NOT NULL,            

    source_system          VARCHAR(50) NOT NULL,
    source_entity          VARCHAR(50) NOT NULL
);


CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_ideas_bk
ON bl_dm.dim_ideas (idea_src_id, source_system, source_entity);


--======================================================================
-- 3. DEFAULT ROW
--======================================================================
BEGIN;

INSERT INTO bl_dm.dim_ideas (
    idea_surr_id,
    idea_src_id,
    idea_title,
    idea_version,
    idea_category_id,
    idea_category_name,
    idea_subcategory_id,
    idea_subcategory_name,
    industry_domain_src_id,
    industry_domain_name,
    author_src_id,
    author_name,
    insert_dt,
    update_dt,
    source_system,
    source_entity
)
SELECT
    -1,
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    'n.a.',
    CURRENT_DATE,
    CURRENT_DATE,
    'MANUAL',
    'MANUAL'
WHERE NOT EXISTS (
    SELECT 1
    FROM bl_dm.dim_ideas
    WHERE idea_surr_id = -1
);

COMMIT;

--======================================================================
-- 4. LOAD: UPDATE changed rows (SCD1)
--======================================================================
BEGIN;

WITH src_raw AS (
    SELECT
        CAST(x.idea_id AS VARCHAR(100))              AS idea_src_id,
        COALESCE(x.idea_title, 'n.a.')               AS idea_title,
        COALESCE(x.idea_version, 'n.a.')             AS idea_version,

        COALESCE(x.category_id, 'n.a.')              AS idea_category_id,
        COALESCE(x.category, 'n.a.')                 AS idea_category_name,

        COALESCE(x.subcategory_id, 'n.a.')           AS idea_subcategory_id,
        COALESCE(x.subcategory, 'n.a.')              AS idea_subcategory_name,

        COALESCE(x.industry_domain_id, 'n.a.')       AS industry_domain_src_id,
        COALESCE(x.industry_domain, 'n.a.')          AS industry_domain_name,

        COALESCE(x.author_id, 'n.a.')                AS author_src_id,
        COALESCE(x.author_name, 'n.a.')              AS author_name,

        COALESCE(x.source_system, 'n.a.')            AS source_system,
        x.source_entity                              AS source_entity
    FROM (
        SELECT
            idea_id, idea_title, idea_version,
            category_id, category,
            subcategory_id, subcategory,
            industry_domain_id, industry_domain,
            author_id, author_name,
            source_system,
            'ext_b2c'::varchar(50) AS source_entity
        FROM sa_b2c.ext_b2c
        WHERE idea_id IS NOT NULL

        UNION ALL

        SELECT
            idea_id, idea_title, idea_version,
            category_id, category,
            subcategory_id, subcategory,
            industry_domain_id, industry_domain,
            author_id, author_name,
            source_system,
            'ext_b2b'::varchar(50) AS source_entity
        FROM sa_b2b.ext_b2b
        WHERE idea_id IS NOT NULL
    ) x
),
src AS (
    /* Deduplicate identical ideas coming from B2C and B2B */
    SELECT
        idea_src_id,
        idea_title,
        idea_version,
        idea_category_id,
        idea_category_name,
        idea_subcategory_id,
        idea_subcategory_name,
        industry_domain_src_id,
        industry_domain_name,
        author_src_id,
        author_name,
        source_system,
        MIN(source_entity) AS source_entity
    FROM src_raw
    GROUP BY
        idea_src_id,
        idea_title,
        idea_version,
        idea_category_id,
        idea_category_name,
        idea_subcategory_id,
        idea_subcategory_name,
        industry_domain_src_id,
        industry_domain_name,
        author_src_id,
        author_name,
        source_system
),
cmp AS (
    SELECT
        s.*,
        d.idea_surr_id,

        d.idea_title             AS d_idea_title,
        d.idea_version           AS d_idea_version,
        d.idea_category_id       AS d_idea_category_id,
        d.idea_category_name     AS d_idea_category_name,
        d.idea_subcategory_id    AS d_idea_subcategory_id,
        d.idea_subcategory_name  AS d_idea_subcategory_name,
        d.industry_domain_src_id AS d_industry_domain_src_id,
        d.industry_domain_name   AS d_industry_domain_name,
        d.author_src_id          AS d_author_src_id,
        d.author_name            AS d_author_name
    FROM src s
LEFT JOIN bl_dm.dim_ideas d
  ON d.idea_src_id   = s.idea_src_id
 AND d.source_system = s.source_system
 AND d.source_entity = s.source_entity
)

UPDATE bl_dm.dim_ideas d
SET
    idea_title             = c.idea_title,
    idea_version           = c.idea_version,
    idea_category_id       = c.idea_category_id,
    idea_category_name     = c.idea_category_name,
    idea_subcategory_id    = c.idea_subcategory_id,
    idea_subcategory_name  = c.idea_subcategory_name,
    industry_domain_src_id = c.industry_domain_src_id,
    industry_domain_name   = c.industry_domain_name,
    author_src_id          = c.author_src_id,
    author_name            = c.author_name,
    update_dt              = CURRENT_DATE,
    source_system          = c.source_system,
    source_entity          = c.source_entity
FROM cmp c
WHERE d.idea_surr_id = c.idea_surr_id
  AND c.idea_surr_id IS NOT NULL
  AND (
       c.idea_title             IS DISTINCT FROM c.d_idea_title
    OR c.idea_version           IS DISTINCT FROM c.d_idea_version
    OR c.idea_category_id       IS DISTINCT FROM c.d_idea_category_id
    OR c.idea_category_name     IS DISTINCT FROM c.d_idea_category_name
    OR c.idea_subcategory_id    IS DISTINCT FROM c.d_idea_subcategory_id
    OR c.idea_subcategory_name  IS DISTINCT FROM c.d_idea_subcategory_name
    OR c.industry_domain_src_id IS DISTINCT FROM c.d_industry_domain_src_id
    OR c.industry_domain_name   IS DISTINCT FROM c.d_industry_domain_name
    OR c.author_src_id          IS DISTINCT FROM c.d_author_src_id
    OR c.author_name            IS DISTINCT FROM c.d_author_name
  );

COMMIT;


--======================================================================
-- 5. LOAD: INSERT new rows (PK generated in DML)
--======================================================================
BEGIN;

WITH src_raw AS (
    SELECT
        CAST(x.idea_id AS VARCHAR(100))              AS idea_src_id,
        COALESCE(x.idea_title, 'n.a.')               AS idea_title,
        COALESCE(x.idea_version, 'n.a.')             AS idea_version,

        COALESCE(x.category_id, 'n.a.')              AS idea_category_id,
        COALESCE(x.category, 'n.a.')                 AS idea_category_name,

        COALESCE(x.subcategory_id, 'n.a.')           AS idea_subcategory_id,
        COALESCE(x.subcategory, 'n.a.')              AS idea_subcategory_name,

        COALESCE(x.industry_domain_id, 'n.a.')       AS industry_domain_src_id,
        COALESCE(x.industry_domain, 'n.a.')          AS industry_domain_name,

        COALESCE(x.author_id, 'n.a.')                AS author_src_id,
        COALESCE(x.author_name, 'n.a.')              AS author_name,

        COALESCE(x.source_system, 'n.a.')            AS source_system,
        x.source_entity                              AS source_entity
    FROM (
        SELECT
            idea_id, idea_title, idea_version,
            category_id, category,
            subcategory_id, subcategory,
            industry_domain_id, industry_domain,
            author_id, author_name,
            source_system,
            'ext_b2c'::varchar(50) AS source_entity
        FROM sa_b2c.ext_b2c
        WHERE idea_id IS NOT NULL

        UNION ALL

        SELECT
            idea_id, idea_title, idea_version,
            category_id, category,
            subcategory_id, subcategory,
            industry_domain_id, industry_domain,
            author_id, author_name,
            source_system,
            'ext_b2b'::varchar(50) AS source_entity
        FROM sa_b2b.ext_b2b
        WHERE idea_id IS NOT NULL
    ) x
),
src AS (
    SELECT
        idea_src_id,
        idea_title,
        idea_version,
        idea_category_id,
        idea_category_name,
        idea_subcategory_id,
        idea_subcategory_name,
        industry_domain_src_id,
        industry_domain_name,
        author_src_id,
        author_name,
        source_system,
        MIN(source_entity) AS source_entity
    FROM src_raw
    GROUP BY
        idea_src_id,
        idea_title,
        idea_version,
        idea_category_id,
        idea_category_name,
        idea_subcategory_id,
        idea_subcategory_name,
        industry_domain_src_id,
        industry_domain_name,
        author_src_id,
        author_name,
        source_system
)
INSERT INTO bl_dm.dim_ideas (
    idea_surr_id,             
    idea_src_id,
    idea_title,
    idea_version,
    idea_category_id,
    idea_category_name,
    idea_subcategory_id,
    idea_subcategory_name,
    industry_domain_src_id,
    industry_domain_name,
    author_src_id,
    author_name,
    insert_dt,
    update_dt,
    source_system,
    source_entity
)
SELECT
    nextval('bl_dm.seq_dim_ideas') AS idea_surr_id,  
    s.idea_src_id,
    s.idea_title,
    s.idea_version,
    s.idea_category_id,
    s.idea_category_name,
    s.idea_subcategory_id,
    s.idea_subcategory_name,
    s.industry_domain_src_id,
    s.industry_domain_name,
    s.author_src_id,
    s.author_name,
    CURRENT_DATE,
    CURRENT_DATE,
    s.source_system,
    s.source_entity
FROM src s
LEFT JOIN bl_dm.dim_ideas d
  ON d.idea_src_id   = s.idea_src_id
 AND d.source_system = s.source_system
 AND d.source_entity = s.source_entity
WHERE d.idea_src_id IS NULL;

COMMIT;


--==========================================================
-- MINIMAL CHECKS FOR BL_DM.DIM_IDEAS
--==========================================================

-- 1) Default row exists
-- Expected: cnt = 1
SELECT
    'CHK_01_DEFAULT_ROW' AS check_name,
    COUNT(*)             AS cnt
FROM bl_dm.dim_ideas
WHERE idea_surr_id = -1;

-- 2) No duplicate business keys
-- Expected: problem_rows = 0
SELECT
    'CHK_02_DUPLICATE_BK' AS check_name,
    COUNT(*)              AS problem_rows
FROM (
    SELECT idea_src_id
    FROM bl_dm.dim_ideas
    GROUP BY idea_src_id
    HAVING COUNT(*) > 1
) t;

-- 3) No NULLs after COALESCE (data quality)
-- Expected: problem_rows = 0
SELECT
    'CHK_03_NULLS_AFTER_LOAD' AS check_name,
    COUNT(*)                  AS problem_rows
FROM bl_dm.dim_ideas
WHERE idea_src_id IS NULL
   OR idea_title IS NULL
   OR idea_category_id IS NULL
   OR industry_domain_src_id IS NULL
   OR author_src_id IS NULL; 
/*======================================================================
  Layer  : BL_DM
  Object : DIM_CONTRACTS
  Type   : DDL + DML (SCD1)
  Source : sa_b2b.ext_b2b (contracts exist only in B2B)

======================================================================*/

--======================================================================
-- 1. SEQUENCE
--======================================================================
CREATE SEQUENCE IF NOT EXISTS bl_dm.seq_dim_contracts
    START WITH 1
    INCREMENT BY 1;

--======================================================================
-- 2. TABLE (NO DEFAULTS)
--======================================================================
CREATE TABLE IF NOT EXISTS bl_dm.dim_contracts (
    contract_surr_id        BIGINT PRIMARY KEY,      
    contract_src_id         VARCHAR(100) NOT NULL,

    purchase_type           VARCHAR(50)  NOT NULL,
    license_type            VARCHAR(50)  NOT NULL,
    seats_cnt               INT          NOT NULL,

    contract_start_dt       DATE         NOT NULL,
    contract_end_dt         DATE         NOT NULL,

    account_manager_src_id  VARCHAR(100) NOT NULL,
    account_manager_name    VARCHAR(255) NOT NULL,

    insert_dt               DATE         NOT NULL,
    update_dt               DATE         NOT NULL,    

    source_system           VARCHAR(50)  NOT NULL,
    source_entity           VARCHAR(50)  NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_dim_contracts_bk
ON bl_dm.dim_contracts (contract_src_id, source_system, source_entity);


--======================================================================
-- 3. DEFAULT ROW
--======================================================================
BEGIN;

INSERT INTO bl_dm.dim_contracts (
    contract_surr_id,
    contract_src_id,
    purchase_type,
    license_type,
    seats_cnt,
    contract_start_dt,
    contract_end_dt,
    account_manager_src_id,
    account_manager_name,
    insert_dt,
    update_dt,
    source_system,
    source_entity
)
SELECT
    -1,
    'n.a.',
    'n.a.',
    'n.a.',
    0,
    DATE '1900-01-01',
    DATE '9999-12-31',
    'n.a.',
    'n.a.',
    CURRENT_DATE,
    CURRENT_DATE,
    'MANUAL',
    'MANUAL'
WHERE NOT EXISTS (
    SELECT 1
    FROM bl_dm.dim_contracts
    WHERE contract_surr_id = -1
);

COMMIT;

--======================================================================
-- 4. LOAD: UPDATE changed rows (SCD1)
--======================================================================
BEGIN;

WITH src_raw AS (
    SELECT
        ct.contract_src_id                                AS contract_src_id,
        COALESCE(ct.purchase_type, 'n.a.')                AS purchase_type,
        COALESCE(ct.license_type, 'n.a.')                 AS license_type,
        COALESCE(ct.seats, 0)                             AS seats_cnt,

        COALESCE(MIN(o.contract_start_dt), DATE '1900-01-01') AS contract_start_dt,
        COALESCE(MAX(o.contract_end_dt),   DATE '9999-12-31') AS contract_end_dt,

        COALESCE(am.account_manager_src_id, 'n.a.')       AS account_manager_src_id,
        COALESCE(am.account_manager_name, 'n.a.')         AS account_manager_name,

        COALESCE(ct.source_system, 'n.a.')                AS source_system,
        COALESCE(ct.source_entity, 'n.a.')                AS source_entity
    FROM bl_3nf.ce_contracts ct
    LEFT JOIN bl_3nf.ce_account_managers am
      ON am.account_manager_id = ct.account_manager_id
    LEFT JOIN bl_3nf.ce_order_lines ol
      ON ol.contract_id = ct.contract_id
    LEFT JOIN bl_3nf.ce_orders o
      ON o.order_id = ol.order_id
    WHERE ct.contract_id <> -1
    GROUP BY
        ct.contract_src_id,
        ct.purchase_type,
        ct.license_type,
        ct.seats,
        am.account_manager_src_id,
        am.account_manager_name,
        ct.source_system,
        ct.source_entity
),
src AS (
    SELECT DISTINCT ON (contract_src_id, source_system, source_entity)
        contract_src_id,
        purchase_type,
        license_type,
        seats_cnt,
        contract_start_dt,
        contract_end_dt,
        account_manager_src_id,
        account_manager_name,
        source_system,
        source_entity
    FROM src_raw
    ORDER BY contract_src_id, source_system, source_entity, contract_start_dt DESC, contract_end_dt DESC
),
cmp AS (
    SELECT
        s.*,
        d.contract_surr_id,

        d.purchase_type           AS d_purchase_type,
        d.license_type            AS d_license_type,
        d.seats_cnt               AS d_seats_cnt,
        d.contract_start_dt       AS d_contract_start_dt,
        d.contract_end_dt         AS d_contract_end_dt,
        d.account_manager_src_id  AS d_account_manager_src_id,
        d.account_manager_name    AS d_account_manager_name
 FROM src s
LEFT JOIN bl_dm.dim_contracts d
  ON d.contract_src_id = s.contract_src_id
 AND d.source_system   = s.source_system
 AND d.source_entity   = s.source_entity
)

UPDATE bl_dm.dim_contracts d
SET
    purchase_type          = c.purchase_type,
    license_type           = c.license_type,
    seats_cnt              = c.seats_cnt,
    contract_start_dt      = c.contract_start_dt,
    contract_end_dt        = c.contract_end_dt,
    account_manager_src_id = c.account_manager_src_id,
    account_manager_name   = c.account_manager_name,
    update_dt              = CURRENT_DATE,
    source_system          = c.source_system,
    source_entity          = c.source_entity
FROM cmp c
WHERE d.contract_surr_id = c.contract_surr_id
  AND c.contract_surr_id IS NOT NULL
  AND (
       c.purchase_type          IS DISTINCT FROM c.d_purchase_type
    OR c.license_type           IS DISTINCT FROM c.d_license_type
    OR c.seats_cnt              IS DISTINCT FROM c.d_seats_cnt
    OR c.contract_start_dt      IS DISTINCT FROM c.d_contract_start_dt
    OR c.contract_end_dt        IS DISTINCT FROM c.d_contract_end_dt
    OR c.account_manager_src_id IS DISTINCT FROM c.d_account_manager_src_id
    OR c.account_manager_name   IS DISTINCT FROM c.d_account_manager_name
  );

COMMIT;

--======================================================================
-- 5. LOAD: INSERT new rows (PK generated in DML)
--======================================================================
BEGIN;

WITH src_raw AS (
    SELECT
        ct.contract_src_id                                AS contract_src_id,
        COALESCE(ct.purchase_type, 'n.a.')                AS purchase_type,
        COALESCE(ct.license_type, 'n.a.')                 AS license_type,
        COALESCE(ct.seats, 0)                             AS seats_cnt,

        COALESCE(MIN(o.contract_start_dt), DATE '1900-01-01') AS contract_start_dt,
        COALESCE(MAX(o.contract_end_dt),   DATE '9999-12-31') AS contract_end_dt,

        COALESCE(am.account_manager_src_id, 'n.a.')       AS account_manager_src_id,
        COALESCE(am.account_manager_name, 'n.a.')         AS account_manager_name,

        COALESCE(ct.source_system, 'n.a.')                AS source_system,
        COALESCE(ct.source_entity, 'n.a.')                AS source_entity
    FROM bl_3nf.ce_contracts ct
    LEFT JOIN bl_3nf.ce_account_managers am
      ON am.account_manager_id = ct.account_manager_id
    LEFT JOIN bl_3nf.ce_order_lines ol
      ON ol.contract_id = ct.contract_id
    LEFT JOIN bl_3nf.ce_orders o
      ON o.order_id = ol.order_id
    WHERE ct.contract_id <> -1
    GROUP BY
        ct.contract_src_id,
        ct.purchase_type,
        ct.license_type,
        ct.seats,
        am.account_manager_src_id,
        am.account_manager_name,
        ct.source_system,
        ct.source_entity
),
src AS (
    SELECT DISTINCT ON (contract_src_id, source_system, source_entity)
        contract_src_id,
        purchase_type,
        license_type,
        seats_cnt,
        contract_start_dt,
        contract_end_dt,
        account_manager_src_id,
        account_manager_name,
        source_system,
        source_entity
    FROM src_raw
    ORDER BY contract_src_id, source_system, source_entity, contract_start_dt DESC, contract_end_dt DESC
)

INSERT INTO bl_dm.dim_contracts (
    contract_surr_id,            
    contract_src_id,
    purchase_type,
    license_type,
    seats_cnt,
    contract_start_dt,
    contract_end_dt,
    account_manager_src_id,
    account_manager_name,
    insert_dt,
    update_dt,
    source_system,
    source_entity
)
SELECT
    nextval('bl_dm.seq_dim_contracts') AS contract_surr_id, 
    s.contract_src_id,
    s.purchase_type,
    s.license_type,
    s.seats_cnt,
    s.contract_start_dt,
    s.contract_end_dt,
    s.account_manager_src_id,
    s.account_manager_name,
    CURRENT_DATE,
    CURRENT_DATE,
    s.source_system,
    s.source_entity
FROM src s
LEFT JOIN bl_dm.dim_contracts d
  ON d.contract_src_id = s.contract_src_id
 AND d.source_system   = s.source_system
 AND d.source_entity   = s.source_entity
WHERE d.contract_src_id IS NULL;

COMMIT;

--==========================================================
-- MINIMAL CHECKS FOR BL_DM.DIM_CONTRACTS
--==========================================================

-- 1) Default row exists
-- Expected: cnt = 1
SELECT
    'CHK_01_DEFAULT_ROW' AS check_name,
    COUNT(*)             AS cnt
FROM bl_dm.dim_contracts
WHERE contract_surr_id = -1;

-- 2) No duplicate business keys
-- Expected: problem_rows = 0
SELECT
    'CHK_02_DUPLICATE_BK' AS check_name,
    COUNT(*)              AS problem_rows
FROM (
    SELECT contract_src_id
    FROM bl_dm.dim_contracts
    GROUP BY contract_src_id
    HAVING COUNT(*) > 1
) t;

-- 3) No NULLs after load (key attributes)
-- Expected: problem_rows = 0
SELECT
    'CHK_03_NULLS_AFTER_LOAD' AS check_name,
    COUNT(*)                  AS problem_rows
FROM bl_dm.dim_contracts
WHERE contract_src_id IS NULL
   OR purchase_type IS NULL
   OR license_type IS NULL
   OR seats_cnt IS NULL
   OR contract_start_dt IS NULL
   OR contract_end_dt IS NULL
   OR account_manager_src_id IS NULL
   OR account_manager_name IS NULL;

/*======================================================================
  Layer  : BL_DM
  Object : FCT_ORDER_LINE_DD
  Type   : DDL + DML
======================================================================*/

--======================================================================
-- 1. TABLE
--======================================================================
CREATE TABLE IF NOT EXISTS bl_dm.fct_order_line_dd (
    event_dt            DATE   NOT NULL,
    order_id            BIGINT NOT NULL,
    order_line_id       BIGINT NOT NULL,

    customer_surr_id    BIGINT NOT NULL,
    date_dt             DATE   NOT NULL,
    contract_surr_id    BIGINT NOT NULL,
    idea_surr_id        BIGINT NOT NULL,

    country_id          BIGINT NOT NULL,
    city_id             BIGINT NOT NULL,

    gross_sales_amount  NUMERIC(15,2) NOT NULL,
    discount_amount     NUMERIC(15,2) NOT NULL,
    net_sales_amount    NUMERIC(15,2) NOT NULL,
    cost_amount         NUMERIC(15,2) NOT NULL,
    support_cost_amount NUMERIC(15,2) NOT NULL,
    quantity_cnt        INT NOT NULL,

    profit_amount       NUMERIC(15,2) NOT NULL,
    insert_dt           DATE NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fct_order_line_grain
ON bl_dm.fct_order_line_dd (order_id, order_line_id, event_dt);

--======================================================================
-- 2. LOAD (INSERT ONLY)
--======================================================================
BEGIN;

WITH src AS (
    SELECT
        o.order_dt                              AS event_dt,
        o.order_dt                              AS date_dt,

        o.order_id                              AS order_id,
        ol.order_line_id                        AS order_line_id,

        c.customer_src_id                       AS customer_src_id,
        c.source_system                         AS customer_source,   -- 'B2B'/'B2C'

        i.idea_src_id                           AS idea_src_id,
        i.source_system                         AS idea_source_system,
        i.source_entity                         AS idea_source_entity,

        ct.contract_src_id                      AS contract_src_id,
        ct.source_system                        AS contract_source_system,
        ct.source_entity                        AS contract_source_entity,


        COALESCE(ci.city_id, -1)                AS city_id,
        COALESCE(ci.country_id, -1)             AS country_id,
        COALESCE(ol.gross_sales_amount, 0)      AS gross_sales_amount,
        COALESCE(ol.discount_amount, 0)         AS discount_amount,
        COALESCE(ol.net_sales_amount, 0)        AS net_sales_amount,
        COALESCE(ol.cost_amount, 0)             AS cost_amount,
        COALESCE(ol.support_cost_amount, 0)     AS support_cost_amount,
        COALESCE(ol.quantity, 0)                AS quantity_cnt
    FROM bl_3nf.ce_order_lines ol
    JOIN bl_3nf.ce_orders o
      ON o.order_id = ol.order_id
	  
    LEFT JOIN bl_3nf.ce_customers_scd c
      ON c.customer_id = o.customer_id
     AND c.is_active = 'Y'

    LEFT JOIN bl_3nf.ce_ideas i
      ON i.idea_id = ol.idea_id

    LEFT JOIN bl_3nf.ce_contracts ct
      ON ct.contract_id = ol.contract_id

    LEFT JOIN bl_3nf.ce_cities ci
      ON ci.city_id = o.city_id

    WHERE o.order_id <> -1
      AND ol.order_line_id <> -1
),
lkp AS (
    SELECT
        s.*,

        COALESCE(dc.customer_surr_id, -1)   AS customer_surr_id,
        COALESCE(di.idea_surr_id, -1)       AS idea_surr_id,
        COALESCE(dct.contract_surr_id, -1)  AS contract_surr_id

    FROM src s

    LEFT JOIN bl_dm.dim_customers_scd dc
      ON dc.customer_src_id = COALESCE(s.customer_src_id, 'n.a.')
     AND dc.customer_source = COALESCE(s.customer_source, 'n.a.')
     AND dc.is_active = 'Y'
    LEFT JOIN bl_dm.dim_ideas di
      ON di.idea_src_id    = COALESCE(s.idea_src_id, 'n.a.')
     AND di.source_system  = COALESCE(s.idea_source_system, 'n.a.')
     AND di.source_entity  = COALESCE(s.idea_source_entity, 'n.a.')

  LEFT JOIN bl_dm.dim_contracts dct
  ON dct.contract_src_id = COALESCE(s.contract_src_id, 'n.a.')
 AND dct.source_system   = COALESCE(s.contract_source_system, 'n.a.')
 AND dct.source_entity   = COALESCE(s.contract_source_entity, 'n.a.')
)
INSERT INTO bl_dm.fct_order_line_dd (
    event_dt,
    order_id,
    order_line_id,
    customer_surr_id,
    date_dt,
    contract_surr_id,
    idea_surr_id,
    country_id,
    city_id,
    gross_sales_amount,
    discount_amount,
    net_sales_amount,
    cost_amount,
    support_cost_amount,
    quantity_cnt,
    profit_amount,
    insert_dt
)
SELECT
    l.event_dt,
    l.order_id,
    l.order_line_id,

    COALESCE(l.customer_surr_id, -1)           AS customer_surr_id,
    l.date_dt,
    COALESCE(l.contract_surr_id, -1)           AS contract_surr_id,
    COALESCE(l.idea_surr_id, -1)               AS idea_surr_id,

    COALESCE(l.country_id, -1)                AS country_id,
    COALESCE(l.city_id, -1)                   AS city_id,

    COALESCE(l.gross_sales_amount, 0)         AS gross_sales_amount,
    COALESCE(l.discount_amount, 0)            AS discount_amount,
    COALESCE(l.net_sales_amount, 0)           AS net_sales_amount,
    COALESCE(l.cost_amount, 0)                AS cost_amount,
    COALESCE(l.support_cost_amount, 0)        AS support_cost_amount,
    COALESCE(l.quantity_cnt, 0)               AS quantity_cnt,

    (
      COALESCE(l.net_sales_amount, 0)
    - COALESCE(l.cost_amount, 0)
    - COALESCE(l.support_cost_amount, 0)
    )                                         AS profit_amount,

    CURRENT_DATE                               AS insert_dt
FROM lkp l
WHERE NOT EXISTS (
    SELECT 1
    FROM bl_dm.fct_order_line_dd f
    WHERE f.order_id = l.order_id
      AND f.order_line_id = l.order_line_id
      AND f.event_dt = l.event_dt
);

COMMIT;



--======================================================================
-- 3. MINIMAL CHECKS
--======================================================================

-- 1) No duplicate grain rows (should be 0)
SELECT
    'CHK_01_DUPLICATE_GRAIN' AS check_name,
    COUNT(*)                 AS problem_rows
FROM (
    SELECT order_id, order_line_id, event_dt
    FROM bl_dm.fct_order_line_dd
    GROUP BY order_id, order_line_id, event_dt
    HAVING COUNT(*) > 1
) t;

-- 2) Profit formula consistency (should be 0)
SELECT
    'CHK_02_PROFIT_FORMULA' AS check_name,
    COUNT(*)                AS problem_rows
FROM bl_dm.fct_order_line_dd
WHERE profit_amount <> (net_sales_amount - cost_amount - support_cost_amount);


